/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package manageGarage;

import com.sun.javafx.scene.text.TextLayout;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class ThemPhuTung extends javax.swing.JInternalFrame {

    /**
     * Creates new form ThemPhuTung
     */
    public ThemPhuTung() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jtxtTenPhuTung = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JtxtGiaPhuTung = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtSoLuongTon = new javax.swing.JTextField();
        bThem = new javax.swing.JButton();
        bDong = new javax.swing.JButton();
        mStatus = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Nhập Phụ Tùng");

        jLabel2.setText("Tên phụ tùng");

        jtxtTenPhuTung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtTenPhuTungActionPerformed(evt);
            }
        });

        jLabel3.setText("Giá phụ tùng");

        jLabel4.setText("Số lượng tồn");

        bThem.setText("Thêm");
        bThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bThemActionPerformed(evt);
            }
        });

        bDong.setText("Đóng");
        bDong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDongActionPerformed(evt);
            }
        });

        mStatus.setText("Status:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(bThem)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(bDong))
                                .addComponent(jtxtSoLuongTon, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(JtxtGiaPhuTung, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addGap(18, 18, 18)
                            .addComponent(jtxtTenPhuTung, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(mStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtTenPhuTung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JtxtGiaPhuTung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtSoLuongTon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bThem)
                    .addComponent(bDong))
                .addGap(18, 18, 18)
                .addComponent(mStatus)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bThemActionPerformed
        // TODO add your handling code here:
        
        
        
        Connection conn = null;
        PreparedStatement ps = null;
        ResultSet rs = null;
        
        String dbURL = "jdbc:sqlserver://127.0.0.1:1433;databaseName=GARAOTO";
        String insert = "INSERT INTO PHUTUNG (TENPT,GIAPT,SLTON) VALUES(?,?,?)";
        
        try {
            conn = DriverManager.getConnection(dbURL,"sa","1");
            ps = conn.prepareStatement(insert);
        } catch (SQLException ex) {
            Logger.getLogger(ThemPhuTung.class.getName()).log(Level.SEVERE, "Loi connect", ex);
        }
            
        try {
            

//            ps.setInt(1,Integer.valueOf(JtxtMaPhuTung.getText()));
            ps.setString(1, jtxtTenPhuTung.getText());
            ps.setInt(2,Integer.valueOf(JtxtGiaPhuTung.getText()));
            ps.setInt(3,Integer.valueOf(jtxtSoLuongTon.getText()));
        if(this.jtxtTenPhuTung.getText().length()==0)
            JOptionPane.showMessageDialog(null, "Tên phụ tùng không được để trống","Thông báo lỗi", 1);
        else
            if(this.jtxtTenPhuTung.getText().length() > 15)
                JOptionPane.showMessageDialog(null, "Tên phụ tùng đã quá 20 kí tự","Thông báo lỗi", 1);
            
          
            int ret = ps.executeUpdate();
            mStatus.setText("Thêm phụ tùng thành công.");
        } catch (Exception e) {
            e.printStackTrace();
           
            
        } finally {
            try {
                if (conn != null) {
                    conn.close();
                }

                if (rs != null) {
                    rs.close();
                }

                if (ps != null) {
                    ps.close();
                }
            } catch (Exception ex2) {
                ex2.printStackTrace();
            }
        }
                                           

                                      
    }//GEN-LAST:event_bThemActionPerformed

    private void bDongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDongActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_bDongActionPerformed

    private void jtxtTenPhuTungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtTenPhuTungActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtTenPhuTungActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JtxtGiaPhuTung;
    private javax.swing.JButton bDong;
    private javax.swing.JButton bThem;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jtxtSoLuongTon;
    private javax.swing.JTextField jtxtTenPhuTung;
    private javax.swing.JLabel mStatus;
    // End of variables declaration//GEN-END:variables
}
